/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER.
 **     Filename    : Aliases.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-07-14, 00:30, # CodeGen: 0
 **     Author      : Dong
 **     Abstract    :
 **          This file contains ports and functions aliases.
 **          Aliases guarantee minimum modification of code,
 **          when ports or functions changed.
 **
 **
 **     Mail        : pzdongdong@163.com
 **
 **     Revision    : No.  Name        Date/Time        Content
 ** ###################################################################*/
/*!
 * @file Aliases.h
 * @version 01.00
 * @brief
 *      This file contains ports and functions aliases.
 *      Aliases guarantee minimum modification of code,
 *      when ports or functions changed.
 *
 */
/*!
 * @addtogroup Ala Alias
 *     This module contains ports and functions aliases.
 *     Aliases guarantee minimum modification of code,
 *     when ports or functions changed.
 * @{
 */

#ifndef ALIASES_H_
#define ALIASES_H_
/* MODULE ALIASES */

#include "Settings.h"

/*
 * ===================================================================
 * Devices Aliases
 * ===================================================================
 */
        /*!
         * @addtogroup DevAla Devices Aliases
         * @{
         */
            /*!
             * @{
             */
#define SYSTICK SysTick_DEVICE
            /*!
             * @}
             */
            /*!
             * @{
             */
#define EINT_SYNC_INT  portA2DevData
#define EINT_NOT_DRDY  portD4DevData
#define IO_START       portB1DevData
#define IO_UPRDY      portB19DevData
#define IO_DAISY_IN    portC1DevData
#define IO_CLKSEL      portC2DevData
#define IO_TEST_SGINAL portC3DevData
#define IO_NOT_PWDN    portE18DevData
#define IO_NOT_RESET   portE19DevData
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_DMA
#define DMA_CTRL      dmaControllerDevData
//#define DMA_CTRL      DMA_CTRL_DeviceDataPtr
#endif
            /*!
             * @{
             */
#if USING_SPI0
#define SPI0 slaveSPI0DevData
#endif
#if USING_SPI1
#define SPI1 masterSPI1DevData
#endif

#if USING_SPI0_DMA
#define SPI0_RX_DMA slaveSPIRxDMADevData
#define SPI0_TX_DMA slaveSPITxDMADevData
#endif
#if USING_SPI1_DMA
#define SPI1_RX_DMA masterSPIRxDMADevData
#define SPI1_TX_DMA masterSPITxDMADevData
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_UART2
#define UART2 uart2DevData
#endif
            /*!
             * @}
             */
        /*!
         * @}
         */

/*
 * ===================================================================
 * Functions Aliases
 * ===================================================================
 */
        /*!
         * @addtogroup FuncAla Functions Aliases
         * @{
         */
            /*!
             * @{
             */
#define SysTickInit()                     SysTick_Init()
#define SysTickWriteReloadValueReg(value) SysTick_PDD_WriteReloadValueReg(SYSTICK, value)
#define SysTickEnable()                   SysTick_PDD_EnableDevice(SYSTICK, PDD_ENABLE)
#define SysTickDisable()                  SysTick_PDD_EnableDevice(SYSTICK, PDD_DISABLE)
#define SysTickClearCountFlag()           SysTick_PDD_ClearInterruptFlag(SYSTICK)
#define SysTickGetCountFlag()             SysTick_PDD_GetInterruptFlag(SYSTICK)
#define SysTickGetClockSource()           SysTick_PDD_GetClkSource(SYSTICK)                     /*!< 0 - External Clock, 1 - Processor Clock.*/
#define SysTickSetClockSource(source)     SysTick_PDD_SetClkSource(SYSTICK, source)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define EIntSyncInterruptInit(userDataPtr)    EINT_SYNC_INT_Init(userDataPtr)
#define EIntSyncInterruptEnable(userDataPtr)  EINT_SYNC_INT_Enable(userDataPtr)
#define EIntSyncInterruptDisable(userDataPtr) EINT_SYNC_INT_Disable(userDataPtr)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IOStartInit(userDataPtr) BitIO_START_Init(userDataPtr)
#define IOStartGetVal()          BitIO_START_GetVal(IO_START)
#define IOStartPutVal(value)     BitIO_START_PutVal(IO_START, value)
#define IOStartClrVal()          BitIO_START_ClrVal(IO_START)
#define IOStartSetVal()          BitIO_START_SetVal(IO_START)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IOUploadReadyInit(userDataPtr) BitIO_UPRDY_Init(userDataPtr)
#define IOUploadReadyGetVal()          BitIO_UPRDY_GetVal(IO_UPRDY)
#define IOUploadReadyPutVal(value)     BitIO_UPRDY_PutVal(IO_UPRDY, value)
#define IOUploadReadyClrVal()          BitIO_UPRDY_ClrVal(IO_UPRDY)
#define IOUploadReadySetVal()          BitIO_UPRDY_SetVal(IO_UPRDY)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IODaisyInInit(userDataPtr) BitIO_DAISY_IN_Init(userDataPtr)
#define IODaisyInGetVal()          BitIO_DAISY_IN_GetVal(IO_DAISY_IN)
#define IODaisyInPutVal(value)     BitIO_DAISY_IN_PutVal(IO_DAISY_IN,value)
#define IODaisyInClrVal()          BitIO_DAISY_IN_ClrVal(IO_DAISY_IN)
#define IODaisyInSetVal()          BitIO_DAISY_IN_SetVal(IO_DAISY_IN)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IOClockSelectInit(userDataPtr) BitIO_CLKSEL_Init(userDataPtr)
#define IOClockSelectGetVal()          BitIO_CLKSEL_GetVal(IO_CLKSEL)
#define IOClockSelectPutVal(value)     BitIO_CLKSEL_PutVal(IO_CLKSEL, value)
#define IOClockSelectClrVal()          BitIO_CLKSEL_ClrVal(IO_CLKSEL)
#define IOClockSelectSetVal()          BitIO_CLKSEL_SetVal(IO_CLKSEL)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define EIntNotReadyInit(userDataPtr)    EINT_NOT_DRDY_Init(userDataPtr)
#define EIntNotReadyEnable(userDataPtr)  EINT_NOT_DRDY_Enable(userDataPtr)
#define EIntNotReadyDisable(userDataPtr) EINT_NOT_DRDY_Disable(userDataPtr)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IONotPowerDownInit(userDataPtr) BitIO_NOT_PWDN_Init(userDataPtr)
#define IONotPowerDownGetVal()          BitIO_NOT_PWDN_GetVal(IO_NOT_PWDN)
#define IONotPowerDownPutVal(value)     BitIO_NOT_PWDN_PutVal(IO_NOT_PWDN, value)
#define IONotPowerDownClrVal()          BitIO_NOT_PWDN_ClrVal(IO_NOT_PWDN)
#define IONotPowerDownSetVal()          BitIO_NOT_PWDN_SetVal(IO_NOT_PWDN)
            /*!
             * @}
             */
            /*!
             * @{
             */
#define IONotResetInit(userDataPtr) BitIO_NOT_RESET_Init(userDataPtr)
#define IONotResetGetVal()          BitIO_NOT_RESET_GetVal(IO_NOT_RESET)
#define IONotResetPutVal(value)     BitIO_NOT_RESET_PutVal(IO_NOT_RESET, value)
#define IONotResetClrVal()          BitIO_NOT_RESET_ClrVal(IO_NOT_RESET)
#define IONotResetSetVal()          BitIO_NOT_RESET_SetVal(IO_NOT_RESET)
            /*!
             * @}
             */
            /*!
             * @{
             */
//#define IOTestSignalInit(userDataPtr) BitIO_TEST_SIGNAL_Init(userDataPtr)
//#define IOTestSignalGetVal()          BitIO_TEST_SIGNAL_GetVal(IO_TEST_SGINAL)
//#define IOTestSignalPutVal(value)     BitIO_TEST_SIGNAL_PutVal(IO_TEST_SGINAL, value)
//#define IOTestSignalClrVal()          BitIO_TEST_SIGNAL_ClrVal(IO_TEST_SGINAL)
//#define IOTestSignalSetVal()          BitIO_TEST_SIGNAL_SetVal(IO_TEST_SGINAL)
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_DMA
#define DMAControllerInit(userDataPtr)                                    DMA_CTRL_Init(userDataPtr)
#define DMAControllerEnable()                                             DMA_CTRL_Enable(DMA_CTRL)
#define DMAControllerDisable()                                            DMA_CTRL_Disable(DMA_CTRL)
#define DMAControllerAllocateChannel(descriptorPtr)                       DMA_CTRL_AllocateChannel(DMA_CTRL, descriptorPtr)
#define DMAControllerEnableChannel(descriptorPtr)                         DMA_CTRL_EnableChannel(DMA_CTRL, descriptorPtr)
#define DMAControllerDisableChannel(descriptorPtr)                        DMA_CTRL_DisableChannel(DMA_CTRL, descriptorPtr)
#define DMAControllerSetChannelSourceAddress(descriptorPtr, address)      DMA_CTRL_SetChannelSourceAddress(DMA_CTRL, descriptorPtr, address)
#define DMAControllerSetChannelDestinationAddress(descriptorPtr, address) DMA_CTRL_SetChannelDestinationAddress(DMA_CTRL, descriptorPtr, address)
#define DMAControllerSetChannelByteCount(descriptorPtr, byteCount)        DMA_CTRL_SetChannelByteCount(DMA_CTRL, descriptorPtr, byteCount)
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_SPI0
#define SPI0Init(userDataPtr)   SS_SPI0_Init(userDataPtr)
#define SPI0Enable()            SS_SPI0_Enable(SPI0)
#define SPI0Disable()           SS_SPI0_Disable(SPI0)
#define SPI0Receive(data, size) SS_SPI0_ReceiveBlock(SPI0, data, size)
#define SPI0Send(data, size)    SS_SPI0_SendBlock(SPI0, data, size)
#define SPI0EnableInterrupt()   SS_SPI0_EnableInterrupt(TRUE, TRUE)
#define SPI0EnableTxInterrupt() SS_SPI0_EnableInterrupt(TRUE, FALSE)
#define SPI0EnableRxInterrupt() SS_SPI0_EnableInterrupt(FALSE, TRUE)
#define SPI0EnableTxDMA()       SPI_PDD_EnableTransmitDma(SPI0_BASE_PTR, PDD_ENABLE)
#define SPI0DisableTxDMA()      SPI_PDD_EnableTransmitDma(SPI0_BASE_PTR, PDD_DISABLE)
#define SPI0EnableRxDMA()       SPI_PDD_EnableReceiveDma(SPI0_BASE_PTR, PDD_ENABLE)
#define SPI0DisableRxDMA()      SPI_PDD_EnableReceiveDma(SPI0_BASE_PTR, PDD_DISABLE)
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_SPI1
#define SPI1Init(userDataPtr)   SM_SPI1_Init(userDataPtr)
#define SPI1Enable()            SM_SPI1_Enable(SPI1)
#define SPI1Disable()           SM_SPI1_Disable(SPI1)
#define SPI1Receive(data, size) SM_SPI1_ReceiveBlock(SPI1, data, size)
#define SPI1Send(data, size)    SM_SPI1_SendBlock(SPI1, data, size)
#define SPI1EnableInterrupt()   SM_SPI1_EnableInterrupt(TRUE, TRUE)
#define SPI1EnableTxInterrupt() SM_SPI1_EnableInterrupt(TRUE, FALSE)
#define SPI1EnableTxDMA()       SPI_PDD_EnableTransmitDma(SPI1_BASE_PTR, PDD_ENABLE)
#define SPI1DisableTxDMA()      SPI_PDD_EnableTransmitDma(SPI1_BASE_PTR, PDD_DISABLE)
#define SPI1EnableRxDMA()       SPI_PDD_EnableReceiveDma(SPI1_BASE_PTR, PDD_ENABLE)
#define SPI1DisableRxDMA()      SPI_PDD_EnableReceiveDma(SPI1_BASE_PTR, PDD_DISABLE)
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_SPI0_DMA
#define SPI0RxDMAInit(userDataPtr)              DMAT_S_SPI_RX_Init(userDataPtr)
#define SPI0RxDMAAllocateChannel()              DMAT_S_SPI_RX_AllocateChannel(SPI0_RX_DMA)
#define SPI0RxDMAEnable()                       DMAT_S_SPI_RX_EnableChannel(SPI0_RX_DMA)
#define SPI0RxDMADisable()                      DMAT_S_SPI_RX_DisableChannel(SPI0_RX_DMA)
#define SPI0RxDMASetSourceAddress(address)      DMAT_S_SPI_RX_SetSourceAddress(SPI0_RX_DMA, address)
#define SPI0RxDMASetDestinationAddress(address) DMAT_S_SPI_RX_SetDestinationAddress(SPI0_RX_DMA, address)
#define SPI0RxDMASetByteCount(address)          DMAT_S_SPI_RX_SetByteCount(SPI0_RX_DMA, address)

#define SPI0TxDMAInit(userDataPtr)              DMAT_S_SPI_TX_Init(userDataPtr)
#define SPI0TxDMAAllocateChannel()              DMAT_S_SPI_TX_AllocateChannel(SPI0_TX_DMA)
#define SPI0TxDMAEnable()                       DMAT_S_SPI_TX_EnableChannel(SPI0_TX_DMA)
#define SPI0TxDMADisable()                      DMAT_S_SPI_TX_DisableChannel(SPI0_TX_DMA)
#define SPI0TxDMASetSourceAddress(address)      DMAT_S_SPI_TX_SetSourceAddress(SPI0_TX_DMA, address)
#define SPI0TxDMASetDestinationAddress(address) DMAT_S_SPI_TX_SetDestinationAddress(SPI0_TX_DMA, address)
#define SPI0TxDMASetByteCount(byteCount)        DMAT_S_SPI_TX_SetByteCount(SPI0_TX_DMA, byteCount)
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_SPI1_DMA
#define SPI1RxDMAInit(userDataPtr)              DMAT_M_SPI_RX_Init(userDataPtr)
#define SPI1RxDMAAllocateChannel()              DMAT_M_SPI_RX_AllocateChannel(SPI1_RX_DMA)
#define SPI1RxDMAEnable()                       DMAT_M_SPI_RX_EnableChannel(SPI1_RX_DMA)
#define SPI1RxDMADisable()                      DMAT_M_SPI_RX_DisableChannel(SPI1_RX_DMA)
#define SPI1RxDMASetSourceAddress(address)      DMAT_M_SPI_RX_SetSourceAddress(SPI1_RX_DMA, address)
#define SPI1RxDMASetDestinationAddress(address) DMAT_M_SPI_RX_SetDestinationAddress(SPI1_RX_DMA, address)
#define SPI1RxDMASetByteCount(address)          DMAT_M_SPI_RX_SetByteCount(SPI1_RX_DMA, address)

#define SPI1TxDMAInit(userDataPtr)              DMAT_M_SPI_TX_Init(userDataPtr)
#define SPI1TxDMAAllocateChannel()              DMAT_M_SPI_TX_AllocateChannel(SPI1_TX_DMA)
#define SPI1TxDMAEnable()                       DMAT_M_SPI_TX_EnableChannel(SPI1_TX_DMA)
#define SPI1TxDMADisable()                      DMAT_M_SPI_TX_DisableChannel(SPI1_TX_DMA)
#define SPI1TxDMASetSourceAddress(address)      DMAT_M_SPI_TX_SetSourceAddress(SPI1_TX_DMA, address)
#define SPI1TxDMASetDestinationAddress(address) DMAT_M_SPI_TX_SetDestinationAddress(SPI1_TX_DMA, address)
#define SPI1TxDMASetByteCount(byteCount)        DMAT_M_SPI_TX_SetByteCount(SPI1_TX_DMA, byteCount)
#endif
            /*!
             * @}
             */
            /*!
             * @{
             */
#if USING_UART2
#define UART2Init(UserDataPtr)   AS_UART2_Init(UserDataPtr)
#define UART2Receive(data, size) AS_UART2_ReceiveBlock(UART2, data, size)
#define UART2Send(data, size)    AS_UART2_SendBlock(UART2, data, size)
#define Print(data)              flagUartSent = FALSE; \
                                 UART2Send(data, sizeof(data)); \
                                 while(!flagUartSent)
#define Printn(data, size)       flagUartSent = FALSE; \
                                 UART2Send(data, size); \
                                 while(!flagUartSent)
#endif
            /*!
             * @}
             */
        /*!
         * @}
         */

    /* END Aliases. */

#endif
/* #ifndef ALIASES_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
