/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : ADC.c
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   : ADS1198
 **     Version     : APRIL 2010-REVISED NOVEMBER 2011
 **     Datasheet   : SBAS471C
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-07-12, 20:06, # CodeGen: 0
 **     Author	    : Dong
 **     Abstract    :
 **			This file contains ADC operation functions.
 **     Settings    :
 **
 **     Contents    :
 **         Init               - void ADCInit(void);
 **         Configure          - LDD_TError ADCConfigure(void);
 **         Enable             - LDD_TError ADCEnable(void);
 **         Disable            - LDD_TError ADCDisable(void);
 **         PowerUp            - LDD_TError ADCPowerUp(void);
 **         PowerDown          - LDD_TError ADCPowerDown(void);
 **         UseInClock         - LDD_TError ADCUseInternalClock(void);
 **         UseExClock         - LDD_TError ADCUseExternalClock(void);
 **         StartConvert       - LDD_TError ADCStartConvertByHardware(void);
 **                            - LDD_TError ADCStartConvertByCommand(void);
 **         StopConvert        - LDD_TError ADCStopConvertByHardware(void);
 **                            - LDD_TError ADCStopConvertByCommand(void);
 **         Reset              - void ADCResetByHardware(void);
 **                            - LDD_TError ADCResetByCommand(void);
 **         DaisyConnect       - LDD_TError ADCDaisyConnect(void);
 **         DirectConnect      - LDD_TError ADCDirectConnect(void);
 **         WakeUp             - LDD_TError ADCWakeUp();
 **         StandBy            - LDD_TError ADCStandBy();
 **         RDATAC             - LDD_TError ADCReadDataContinuous(void);
 **         SDATAC             - LDD_TError ADCStopDataContinuous(void);
 **         SendCommand        - LDD_TError ADCSendCommand(byte* cmd);
 **         ReadRegister       - LDD_TError ADCReadRegister(byte regAddr, byte* dat, uint8 n);
 **         WriteRegister      - LDD_TError ADCWriteRegister(byte regAddr, byte* dat, uint8 n);
 **         ReadData           - LDD_TError ADCReadContinuousData(byte* dat, uint8 n);
 **                            - LDD_TError ADCReadData(byte* dat, uint8 n);
 **         ADCDataInit        - ADCDataInit(TADCDataPtr userDataPtr);
 **         CheckCommand       - LDD_TError CheckCommand(byte cmd);
 **
 **     Mail      	: pzdongdong@163.com
 **     
 **     Revision    : No.  Name        Date/Time        Content
 ** ###################################################################*/
/*!
 * @file ADC.c
 * @version 01.00
 * @brief	
 * 		This file contains ADC operation functions.
 */
/*!
 *  @addtogroup ADC_module	ADC module documentation
 *      This module contains ADC operation functions.
 *  @{
 */

/* MODULE ADC. */

/* {Default RTOS Adapter} No RTOS includes */
#include "SM_SPI1.h"
#include "BitIO_NOT_PWDN.h"
#include "BitIO_NOT_RESET.h"
#include "BitIO_START.h"
#include "BitIO_DAISY_IN.h"
#include "BitIO_CLKSEL.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

#include "limits.h"
#include "string.h"
#include "stdlib.h"

#include "MyHeaders.h"


static LDD_TError CheckCommand(byte cmd);

/* 
 * ===================================================================
 * Global Variables
 * ===================================================================
 */

/*
 * ===================================================================
 *     Method      :  ADCInit (Component ADC)
 */
/*!
 *     @brief
 *          Initializes ADC. 
 *          The method is called in the PeripheralInit function and will be called
 *          only once.
 */
/* ===================================================================*/
void ADCInit(void)
{ 
    ADCEnable();                /* Clear ~CS, select ADC */
    DelaySomeMs(1);
    ADCUseInternalClock();      /* Set CLKSEL, ADC uses internal clock  */
    DelaySomeMs(1);
    ADCStopConvertByHardware(); /* Clear START, ADC does not convert */
    DelaySomeMs(1);
    ADCPowerUp();               /* Set ~PWDN */
    DelaySomeMs(1);
//    ADCDirectConnect();         /* Use direct connect mode */
    ADCResetByHardware();       /* Reset ADC when power on */
    DelaySomeMs(1);
    ADCConfigure();             /* Configure the register of ADC. */
}

/*
 * ===================================================================
 *     Method      :  ADCEnable (Component ADC)
 */
/*!
 *     @brief
 *          Signal ~CS is low, enable ADC.
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCEnable(void)
{
//    LDD_TError err;
    
    return ERR_OK;
}

/*
 * ===================================================================
 *     Method      :  ADCDisable (Component ADC)
 */
/*!
 *     @brief
 *          Signal ~CS is High, disable ADC. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCDisable(void)
{
//    LDD_TError err;
    
    return ERR_OK;
}

/*
 * ===================================================================
 *     Method      : ADCConfigure (Module ADC)
 */
/*!
 *     @brief
 *          Configure the registers of ADC via SPI1.    
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCConfigure(void)
{
//    LDD_TError err;
    
    return ERR_OK;
}

/*
 * ===================================================================
 *     Method      :  ADCPowerUp (Component ADC)
 */
/*!
 *     @brief
 *          Signal ~PWDN is high, ADC power up. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCPowerUp(void)
{
    LDD_TError err;
    
    IONotResetSetVal(); /* Set ~PWDN, ADC power up */
    
    if(!IONotResetGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCPowerDown (Component ADC)
 */
/*!
 *     @brief
 *          Signal ~PWDN is low, ADC power down. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCPowerDown(void)
{
    LDD_TError err;
    
    IONotResetClrVal(); /* Clear ~PWDN, ADC power down */
    
    if(IONotResetGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCUseInternalClock (Component ADC)
 */
/*!
 *     @brief
 *          Signal CLKSEL is high, ADC uses internal clock. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCUseInternalClock(void)
{
    LDD_TError err;
    
    IOClockSelectSetVal(); /* Set CLKSEL, use internal clock */
    
    if(!IOClockSelectGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCUseExternalClock (Component ADC)
 */
/*!
 *     @brief
 *          Signal CLKSEL is low, ADC uses external clock. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCUseExternalClock(void)
{
    LDD_TError err;
    
    IOClockSelectClrVal(); /* Clear CLKSEL, use external clock */
    
    if(IOClockSelectGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCStartConvertByHardware (Component ADC)
 */
/*!
 *     @brief
 *          Signal START is high, ADC starts to convert.
 *          This function starts ADC to convert via signal START.
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCStartConvertByHardware(void)
{
    LDD_TError err;
    
    IOStartSetVal(); /* Set START, ADC starts to convert */
    
    if(!IOStartGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCStartConvertByCommand (Component ADC)
 */
/*!
 *     @brief
 *          MCU sends START command to ADC, ADC starts to convert.
 *          This function starts ADC to convert via SPI1.
 *          In this method, signal START must be low.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCStartConvertByCommand(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_START;
    
    IOStartClrVal(); /* Clear START, in this method, signal START must be low */
    
    /* Sends START command via SPI1 */
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCStopConvertByHardware (Component ADC)
 */
/*!
 *     @brief
 *          Signal START is low, ADC stops converting.
 *          This function starts ADC to convert via signal START.
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCStopConvertByHardware(void)
{
    LDD_TError err;
    
    IOStartClrVal(); /* Clear START, ADC does not convert */
    
    if(IOStartGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCStartConvertByCommand (Component ADC)
 */
/*!
 *     @brief
 *          MCU sends STOP command to ADC, ADC stops to convert.
 *          This function stops ADC to convert via SPI1.
 *          In this method, signal START must be low.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCStopConvertByCommand(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_STOP;
    
    IOStartClrVal(); /* Clear START, in this method, signal START must be low */
    
    /* Sends STOP command via SPI1 */
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCResetByHardware (Component ADC)
 */
/*!
 *     @brief
 *          Signal ~RESET varies from high to low to high, ADC resets. 
 *          This function resets ADC via signal RESET.
 */
/* ===================================================================*/
void ADCResetByHardware(void)
{
    IONotResetSetVal(); /* Set ~RESET */
    DelaySomeMs(100);
    IONotResetClrVal(); /* Clear ~RESET, reset ADC */
    DelaySomeMs(100);
    IONotResetSetVal(); /* Set ~RESET */
}

/*
 * ===================================================================
 *     Method      :  ADCResetByCommand (Component ADC)
 */
/*!
 *     @brief
 *          MCU sends RESET command to ADC, ADC resets.
 *          This function resets ADC via SPI1.
 *          Avoid sending any commands during reset.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCResetByCommand(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_RESET;
    
    /* Sends RESET command via SPI1 */
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*  
 * ===================================================================
 *     Method      :  ADCDaisyConnect (Component ADC)
 */
/*!
 *     @brief
 *          Signal Daisy_IN is high, ADC connects in daisy mode. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCDaisyConnect(void)
{
    LDD_TError err;
    
    IODaisyInSetVal(); /* Set DIASY_IN high, connect ADC in daisy mode */
    
    if(!IODaisyInGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      :  ADCDirectConnect (Component ADC)
 */
/*!
 *     @brief
 *          Signal Daisy_IN is low, ADC connects in direct mode. 
 *     @return
 *                          - ERR_OK: Output of this pin is OK.
 *                          - ERR_COMMON: Output of this pin goes wrong.
 */
/* ===================================================================*/
LDD_TError ADCDirectConnect(void)
{
    LDD_TError err;
    
    IODaisyInClrVal(); /* Clear DIASY_IN high, connect ADC in direct mode */
    
    if(IODaisyInGetVal())
    {
        err = ERR_COMMON;
        PrintErrorMessage(err);
    }
    else
    {
        err = ERR_OK;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCWakeUp (Component ADC)
 */
/*!
 *     @brief
 *          Send command WAKEUP to ADC via SPI1 to wake up ADC
 *          from low-power standby mode.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCWakeUp(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_WAKEUP;

    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCStandBy (Component ADC)
 */
/*!
 *     @brief
 *          Send command STANDBY via SPI1 to make ADC entering
 *          the low-power standby mode.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCStandBy(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_STANDBY;
    
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCReadDataContinuous (Component ADC)
 */
/*!
 *     @brief
 *          Send command RDATAC via SPI1 to make the conversion data
 *          of ADC can read continuously without command RDATA.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCReadDataContinuous(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_RDATAC;
    
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCWakeUp (Component ADC)
 */
/*!
 *     @brief
 *          Send command SDATAC to ADC via SPI1 to stop ADC's RDATAC mode.
 *     @return
 *                          - See PE_Error.h
 */
/* ===================================================================*/
LDD_TError ADCStopReadDataContinuous(void)
{
    LDD_TError err;
    byte cmd = ADC_CMD_SDATAC;
    
    err = ADCSendCommand(&cmd);
    DelaySomeMs(1);
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCSendCommand (Component ADC)
 */
/*!
 *     @brief
 *          Send command to ADC via SPI1. Please use ADCReadRegister and
 *          ADCWriteRegister, but not this function, to read and write ADC's register!
 *     @param[in]
 *          cmd             - Pointer to command to be sent.
 *                            See group ADC Commands in Macros.h.
 *     @return
 *                          - Error code of the the transmission status.
 *                          - Possible codes:             
 *                              - ERR_OK       - OK.
 *                              - ERR_SPEED    - This device does not work in
 *                                               the active clock configuration.
 *                              - ERR_DISABLED - Component is disabled.
 *                              - ERR_BUSY     - The previous receive request is
 *                                               pending.
 *                              - etc.         - See PE_Error.h.
 */
/* ===================================================================*/
LDD_TError ADCSendCommand(byte* cmd)
{
    LDD_TError err;
    uint8 len;
    byte dummy;
    
    /* Check the command. */
    err = CheckCommand(*cmd);
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
        return err;
    }
    
    len = ((*cmd) < ADC_CMD_RREG(0x00)) ? 1 : 2;
    
    /* Try to send the command to ADC. */
    err = SPI1ReceiveSendData((LDD_DMA_TAddress)cmd, (LDD_DMA_TAddress)(&dummy),
                              (LDD_DMA_TByteCount)len, (LDD_DMA_TByteCount)len);
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);         /* If error occurred, print the error message, */
        return err;                     /* then return error type. */
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCReadRegister (Component ADC)
 */
/*!
 *     @brief
 *          Read data from register of ADC via SPI1. The first two bytes are useless,
 *          the real data starts at index 2!!!
 *     @param[in]
 *          regAddr         - The first address of register(s) to be read.
 *     @param[out]
 *          dat             - Pointer to the buffer where received data in.
 *     @param[in]
 *          n               - The number of registers to be read.
 *     @return
 *                          - Error code of the the transmission status.
 *                          - Possible codes:             
 *                              - ERR_OK       - OK.             
 *                              - ERR_SPEED    - This device does not work in
 *                                               the active clock configuration.           
 *                              - ERR_DISABLED - Component is disabled.
 *                              - ERR_BUSY     - The previous receive request is
 *                                               pending.
 *                              - etc.         - See PE_Error.h.
 */                                
/* ===================================================================*/
LDD_TError ADCReadRegister(byte regAddr, byte* dat, uint8 n)
{
    LDD_TError err;
    byte strCmd[2];                 /* The read register command is a 2-byte command. */
    
    /* Check if the register address is valid. */
    if(regAddr < ADC_REG_ID || regAddr > ADC_REG_WCT2)
    {
        err = ERR_PARAM_ADDRESS;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the reception buffer is valid. */
    if(!dat)
    {
        err = ERR_PARAM_BUFFER_COUNT;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the number of registers to be read is valid. */
    if(n < MIN_REGISTER_READ_NUMBER || n > MAX_REGISTER_READ_NUMBER)
    {
        err = ERR_RANGE;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Prepare the command and the register number. */
    strCmd[0] = ADC_CMD_RREG(regAddr);              /* According to user manual, read ADC register command, */
    strCmd[1] = n - 1;                              /* and if the number of registers to be read is n, n - 1 should be sent to ADC. */

    /* Try to send and receive the data.
     * Remember that the dat[0] and dat[1] are useless!!!
     * The real data begins at dat[2]!!! */
    err = SPI1ReceiveSendData((LDD_DMA_TAddress)strCmd, (LDD_DMA_TAddress)dat,
                              (LDD_DMA_TByteCount)(n + 2), (LDD_DMA_TByteCount)(n + 2));
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
#if DEBUG
        printf("Send command error\n");             /* If error occurred, print message, */
#endif
        return err;                                 /* then return the error type. */
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCWriteRegister (Component ADC)
 */
/*!
 *     @brief
 *          Write data to register of ADC via SPI1.
 *     @param[in]
 *          regAddr         - The first address of register(s) to be written.
 *     @param[in]
 *          dat             - Pointer to buffer where data to be written in.
 *     @param[in]
 *          n               - The number of registers to be written.
 *     @return
 *                          - Error code of the the transmission status.
 *                          - Possible codes:             
 *                              - ERR_OK           - OK.             
 *                              - ERR_SPEED        - This device does not work in
 *                                                   the active clock configuration.           
 *                              - ERR_DISABLED     - Component is disabled.
 *                              - ERR_BUSY         - The previous receive request is
 *                                                   pending.
 *                              - etc.             - See PE_Error.h.
 */                                
/* ===================================================================*/
LDD_TError ADCWriteRegister(byte regAddr, byte* dat, uint8 n)
{
    LDD_TError err;
    byte strCmd[REGISTER_NUMBER + 2];                   /* Write register command is a double-byte command. */
    byte dummy[REGISTER_NUMBER + 2];                    /* Receive dummy message. */
    uint8 i;
    
    /* Check if the register address is valid. */
    if(regAddr < ADC_REG_ID || regAddr > ADC_REG_WCT2)
    {
        err = ERR_PARAM_ADDRESS;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the transmission buffer is valid. */
    if(!dat)
    {
        err = ERR_PARAM_BUFFER_COUNT;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the number of registers to be written is valid. */
    if(n < MIN_REGISTER_READ_NUMBER || n > MAX_REGISTER_READ_NUMBER)
    {
        err = ERR_RANGE;
        PrintErrorMessage(err);
        
        return err;
    }

    /* Send the write data command to ADC. */
    strCmd[0] = ADC_CMD_WREG(regAddr);              /* According to user manual, write ADC register command, */
    strCmd[1] = n - 1;                              /* and if the number of registers to be written is n, n - 1 should be sent to ADC. */
    for(i = 0; i < n; i++)
    {
        strCmd[i + 2] = dat[i];
    }
    
    err = SPI1ReceiveSendData((LDD_DMA_TAddress)strCmd, (LDD_DMA_TAddress)dummy,
                              (LDD_DMA_TByteCount)(n + 2), (LDD_DMA_TByteCount)(n + 2));
    
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
        printf("Send command error\n");             /* If error occurred, print message, */
        
        return err;                                 /* then return the error type. */
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCReadContinuousData (Component ADC)
 */
/*!
 *     @brief
 *          Read conversion data from ADC in RDATAC mode via SPI1.
 *     @param[out]
 *          dat             - Pointer to buffer where received data in.
 *     @param[in]
 *          n               - The length of data bytes to be read.
 *     @return
 *                          - Error code of the the transmission status.
 *                          - Possible codes:             
 *                              - ERR_OK       - OK.             
 *                              - ERR_SPEED    - This device does not work in
 *                                               the active clock configuration.           
 *                              - ERR_DISABLED - Component is disabled.
 *                              - ERR_BUSY     - The previous receive request is
 *                                               pending.
 *                              - etc.         - See PE_Error.h.
 */  
/* ===================================================================*/
LDD_TError ADCReadContinuousData(byte* dat, uint8 n)
{
    LDD_TError err;
    byte dummy[RAW_DATA_SIZE];
    
    /* Check if the reception buffer is valid. */
    if(!dat)
    {
        err = ERR_PARAM_BUFFER_COUNT;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the length of data bytes is valid. */
    if(n < 0 || n > RAW_DATA_SIZE)
    {
        err = ERR_PARAM_LENGTH;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Try to receive data. */
    err = SPI1ReceiveSendData((LDD_DMA_TAddress)dummy, (LDD_DMA_TAddress)dat,
                              (LDD_DMA_TByteCount)n, (LDD_DMA_TByteCount)n);
    if(err != ERR_OK)
    {
        PrintErrorMessage(err);
#if DEBUG
        printf("Send dummy error\n");
#endif        
        return err;
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCReadData (Component ADC)
 */
/*!
 *     @brief
 *          Read conversion data from ADC in RDATA mode via SPI1. The first byte is useless,
 *          the real data starts at index 1!!!
 *     @param[out]
 *          dat             - Pointer to buffer where received data in.
 *     @param[in]
 *          n               - The length of data bytes to be read.
 *     @return
 *                          - Error code of the the transmission status.
 *                          - Possible codes:             
 *                              - ERR_OK       - OK.             
 *                              - ERR_SPEED    - This device does not work in
 *                                               the active clock configuration.           
 *                              - ERR_DISABLED - Component is disabled.
 *                              - ERR_BUSY     - The previous receive request is
 *                                               pending.
 *                              - etc.         - See PE_Error.h.
 */                                
/* ===================================================================*/
LDD_TError ADCReadData(byte* dat, uint8 n)
{
    LDD_TError err;
    byte strCmd[RAW_DATA_SIZE + 1];
    
    /* Check if the reception buffer is valid. */
    if(!dat)
    {
        err = ERR_PARAM_BUFFER_COUNT;
        PrintErrorMessage(err);
        
        return err;
    }
    
    /* Check if the length of data bytes is valid. */
    if(n < 0 || n > RAW_DATA_SIZE)
    {
        err = ERR_PARAM_LENGTH;
        PrintErrorMessage(err);
        
        return err;
    }
    
    strCmd[0] = ADC_CMD_RDATA;
    /* Try to send and receive the data.
     * Remember that the dat[0] is useless!!!
     * The real data begins at dat[1]!!! */
    err = SPI1ReceiveSendData((LDD_DMA_TAddress)strCmd, (LDD_DMA_TAddress)dat,
                        (LDD_DMA_TByteCount)(n + 1), (LDD_DMA_TByteCount)(n + 1));
    if(err != ERR_OK)
    {
#if DEBUG
        printf("Send command error\n");             /* If error occurred, print message, */
#endif
        return err;                                 /* then return the error type. */
    }
    
    return err;
}

/*
 * ===================================================================
 *     Method      : ADCDataInit(Module ADC)
 */
/*!
 *     @brief
 *         	This method initialize the ADC data structure.
 *     @param
 *         	userDataPtr     - Pointer to specific user data. 
 *     @return
 *         	                - ADC data structure.
 */
/* ===================================================================*/
TADCData ADCDataInit(TADCDataPtr userDataPtr)
{
    TADCData data;

    data.head = (!userDataPtr) ? 0xFFU : userDataPtr->head;
    data.loffStatP = (!userDataPtr) ? 0xFFU : userDataPtr->loffStatP;
    data.loffStatN = (!userDataPtr) ? 0xFFU : userDataPtr->loffStatN;
    data.regGPIOData = (!userDataPtr) ? 0xFFU : userDataPtr->regGPIOData;
    memset(data.rawData, 0xFFU, sizeof(data.rawData));
    memset(data.channelData, 0xFF, sizeof(data.channelData));

    return data;
}

/*
 * ===================================================================
 *     Method      : CheckCommand (Module ADC)
 */
/*!
 *     @brief
 *         	This method checks if the command is valid.
 *     @param[in]
 *         	cmd             - Command to be checked.
 *     @return
 *         	                - ERR_OK: Command is valid and the length is legal.
 *         	                - ERR_PARAM_COMMAND: Command is invalid.
 *         	                - ERR_PARAM_LENGTH: Length is illegal.
 */
/* ===================================================================*/
static LDD_TError CheckCommand(byte cmd)
{
    if(cmd != ADC_CMD_WAKEUP  &&
       cmd != ADC_CMD_STANDBY &&
       cmd != ADC_CMD_RESET   &&
       cmd != ADC_CMD_START   &&
       cmd != ADC_CMD_STOP    &&
       cmd != ADC_CMD_RDATAC  &&
       cmd != ADC_CMD_SDATAC  &&
       cmd != ADC_CMD_RDATA   &&
       (cmd < ADC_CMD_RREG(ADC_REG_ID) || cmd > ADC_CMD_RREG(ADC_REG_WCT2)) &&
       (cmd < ADC_CMD_WREG(ADC_REG_ID) || cmd > ADC_CMD_WREG(ADC_REG_WCT2))
      )
    {
        return ERR_PARAM_COMMAND; 
    }
    
    return ERR_OK;
}

/* END ADC. */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
