/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : EINT_SYNC_INT.h
**     Project     : ProcessorExpert
**     Processor   : MKL15Z128VLH4
**     Component   : ExtInt_LDD
**     Version     : Component 02.154, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-09-24, 19:03, # CodeGen: 161
**     Abstract    :
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings    :
**          Component name                                 : EINT_SYNC_INT
**          Pin                                            : TSI0_CH3/PTA2/UART0_TX/TPM2_CH1
**          Pin signal                                     : SYNC_INT
**          Generate interrupt on                          : both edges
**          Interrupt                                      : INT_PORTA
**          Interrupt priority                             : low priority
**          Initialization                                 : 
**            Enabled in init. code                        : no
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnInterrupt                                : Enabled
**          Threshold level                                : 0
**     Contents    :
**         Init    - LDD_TDeviceData* EINT_SYNC_INT_Init(LDD_TUserData *UserDataPtr);
**         Enable  - void EINT_SYNC_INT_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable - void EINT_SYNC_INT_Disable(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file EINT_SYNC_INT.h
** @version 01.00
** @brief
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
*/         
/*!
**  @addtogroup EINT_SYNC_INT_module EINT_SYNC_INT module documentation
**  @{
*/         

#ifndef __EINT_SYNC_INT_H
#define __EINT_SYNC_INT_H

/* MODULE EINT_SYNC_INT. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"
#include "PORT_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define EINT_SYNC_INT_PRPH_BASE_ADDRESS  0x400FF000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define EINT_SYNC_INT_Init_METHOD_ENABLED /*!< Init method of the component EINT_SYNC_INT is enabled (generated) */
#define EINT_SYNC_INT_Enable_METHOD_ENABLED /*!< Enable method of the component EINT_SYNC_INT is enabled (generated) */
#define EINT_SYNC_INT_Disable_METHOD_ENABLED /*!< Disable method of the component EINT_SYNC_INT is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define EINT_SYNC_INT_OnInterrupt_EVENT_ENABLED /*!< OnInterrupt event of the component EINT_SYNC_INT is enabled (generated) */

/* Definition of implementation constants */
#define EINT_SYNC_INT_PIN_INDEX 0x02U  /*!< Index of the used pin from the port */
#define EINT_SYNC_INT_PIN_MASK 0x04U   /*!< Mask of the used pin from the port */
#define EINT_SYNC_INT_MODULE_BASE_ADDRESS PTA_BASE_PTR /*!< Name of macro used as the base address */
#define EINT_SYNC_INT_PORTCONTROL_BASE_ADDRESS PORTA_BASE_PTR /*!< Name of macro used as the base address */
#define EINT_SYNC_INT_IRQ_CONFIG PORT_PDD_INTERRUPT_ON_RISING_FALLING /*!< Static IRQ configuration */

/*
** ===================================================================
**     Method      :  EINT_SYNC_INT_Init (component ExtInt_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* EINT_SYNC_INT_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  EINT_SYNC_INT_Enable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EINT_SYNC_INT_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  EINT_SYNC_INT_Disable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EINT_SYNC_INT_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  EINT_SYNC_INT_Interrupt (component ExtInt_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(EINT_SYNC_INT_Interrupt);

/* END EINT_SYNC_INT. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __EINT_SYNC_INT_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.07]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
