/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : EINT_NOT_DRDY.c
**     Project     : ProcessorExpert
**     Processor   : MKL15Z128VLH4
**     Component   : ExtInt_LDD
**     Version     : Component 02.154, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-09-09, 15:23, # CodeGen: 125
**     Abstract    :
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings    :
**          Component name                                 : EINT_NOT_DRDY
**          Pin                                            : PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4
**          Pin signal                                     : NOT_DRDY
**          Generate interrupt on                          : falling edge
**          Interrupt                                      : INT_PORTD
**          Interrupt priority                             : low priority
**          Initialization                                 : 
**            Enabled in init. code                        : no
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnInterrupt                                : Enabled
**          Threshold level                                : 0
**     Contents    :
**         Init    - LDD_TDeviceData* EINT_NOT_DRDY_Init(LDD_TUserData *UserDataPtr);
**         Enable  - void EINT_NOT_DRDY_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable - void EINT_NOT_DRDY_Disable(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file EINT_NOT_DRDY.c
** @version 01.00
** @brief
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
*/         
/*!
**  @addtogroup EINT_NOT_DRDY_module EINT_NOT_DRDY module documentation
**  @{
*/         

/* MODULE EINT_NOT_DRDY. */

#include "Events.h"
#include "EINT_NOT_DRDY.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  bool UserEnabled;                    /* Enable/disable device flag */
  LDD_TUserData *UserData;             /* RTOS device data structure */
} EINT_NOT_DRDY_TDeviceData, *EINT_NOT_DRDY_TDeviceDataPtr; /* Device data structure type */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static EINT_NOT_DRDY_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static EINT_NOT_DRDY_TDeviceData * INT_PORTD__DEFAULT_RTOS_ISRPARAM;

/*
** ===================================================================
**     Method      :  EINT_NOT_DRDY_Init (component ExtInt_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* EINT_NOT_DRDY_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  EINT_NOT_DRDY_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Store the UserData pointer */
  DeviceDataPrv->UserData = UserDataPtr;
  /* Set device as Disable */
  DeviceDataPrv->UserEnabled = FALSE;
  /* Interrupt vector(s) allocation */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_PORTD__DEFAULT_RTOS_ISRPARAM = DeviceDataPrv;
  /* Clear interrupt status flag - w1c */
  PORTD_ISFR = PORT_ISFR_ISF(0x10);                                   
  /* Initialization of Port Control registers */
  /* PORTD_PCR4: ISF=0,IRQC=0,MUX=1 */
  PORTD_PCR4 = (uint32_t)((PORTD_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_IRQC(0x0F) |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* NVIC_IPR7: PRI_31=0x80 */
  NVIC_IPR7 = (uint32_t)((NVIC_IPR7 & (uint32_t)~(uint32_t)(
               NVIC_IP_PRI_31(0x7F)
              )) | (uint32_t)(
               NVIC_IP_PRI_31(0x80)
              ));                                  
  /* NVIC_ISER: SETENA|=0x80000000 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x80000000);                                   
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_EINT_NOT_DRDY_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  EINT_NOT_DRDY_Enable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EINT_NOT_DRDY_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  EINT_NOT_DRDY_TDeviceData *DeviceDataPrv = (EINT_NOT_DRDY_TDeviceData *)DeviceDataPtr;

  PORT_PDD_ClearPinInterruptFlag(EINT_NOT_DRDY_PORTCONTROL_BASE_ADDRESS, EINT_NOT_DRDY_PIN_INDEX);
  PORT_PDD_SetPinInterruptConfiguration(EINT_NOT_DRDY_PORTCONTROL_BASE_ADDRESS, EINT_NOT_DRDY_PIN_INDEX, EINT_NOT_DRDY_IRQ_CONFIG);
  DeviceDataPrv->UserEnabled = TRUE;   /* Set device as Enabled */
}

/*
** ===================================================================
**     Method      :  EINT_NOT_DRDY_Disable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EINT_NOT_DRDY_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  EINT_NOT_DRDY_TDeviceData *DeviceDataPrv = (EINT_NOT_DRDY_TDeviceData *)DeviceDataPtr;

  PORT_PDD_SetPinInterruptConfiguration(EINT_NOT_DRDY_PORTCONTROL_BASE_ADDRESS, EINT_NOT_DRDY_PIN_INDEX, PORT_PDD_INTERRUPT_DMA_DISABLED);
  DeviceDataPrv->UserEnabled = FALSE;  /* Set device as Disabled */
}

/*
** ===================================================================
**     Method      :  EINT_NOT_DRDY_Interrupt (component ExtInt_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(EINT_NOT_DRDY_Interrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  EINT_NOT_DRDY_TDeviceDataPtr DeviceDataPrv = INT_PORTD__DEFAULT_RTOS_ISRPARAM;
  /* Check if device is disabled */
  if (!DeviceDataPrv->UserEnabled) {
    return;
  }
  /* Clear the interrupt flag */
  PORT_PDD_ClearPinInterruptFlag(EINT_NOT_DRDY_PORTCONTROL_BASE_ADDRESS, EINT_NOT_DRDY_PIN_INDEX);
  /* Call OnInterrupt event */
  EINT_NOT_DRDY_OnInterrupt(DeviceDataPrv->UserData);
}

/* END EINT_NOT_DRDY. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.07]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
