/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : WaitTimer.h
**     Project     : ProcessorExpert
**     Processor   : MKL15Z128VLH4
**     Component   : TimerUnit_LDD
**     Version     : Component 01.158, Driver 01.11, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-03-05, 18:21, # CodeGen: 179
**     Abstract    :
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
**     Settings    :
**          Component name                                 : WaitTimer
**          Module name                                    : PIT
**          Counter                                        : PIT_CVAL0
**          Counter direction                              : Down
**          Counter width                                  : 32 bits
**          Value type                                     : Optimal
**          Input clock source                             : Internal
**            Counter frequency                            : 24 MHz
**          Counter restart                                : On-match
**            Period device                                : PIT_LDVAL0
**            Period                                       : 10 ms
**            Interrupt                                    : Enabled
**              Interrupt                                  : INT_PIT
**              Interrupt priority                         : medium priority
**          Channel list                                   : 0
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnCounterRestart                           : Enabled
**              OnChannel0                                 : Disabled
**              OnChannel1                                 : Disabled
**              OnChannel2                                 : Disabled
**              OnChannel3                                 : Disabled
**              OnChannel4                                 : Disabled
**              OnChannel5                                 : Disabled
**              OnChannel6                                 : Disabled
**              OnChannel7                                 : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init           - LDD_TDeviceData* WaitTimer_Init(LDD_TUserData *UserDataPtr);
**         Enable         - LDD_TError WaitTimer_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable        - LDD_TError WaitTimer_Disable(LDD_TDeviceData *DeviceDataPtr);
**         SetPeriodTicks - LDD_TError WaitTimer_SetPeriodTicks(LDD_TDeviceData *DeviceDataPtr,...
**         ResetCounter   - LDD_TError WaitTimer_ResetCounter(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file WaitTimer.h
** @version 01.11
** @brief
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
*/         
/*!
**  @addtogroup WaitTimer_module WaitTimer module documentation
**  @{
*/         

#ifndef __WaitTimer_H
#define __WaitTimer_H

/* MODULE WaitTimer. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "PIT_PDD.h"
#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


#ifndef __BWUserType_WaitTimer_TValueType
#define __BWUserType_WaitTimer_TValueType
  typedef uint32_t WaitTimer_TValueType ; /* Type for data parameters of methods */
#endif
#define WaitTimer_CNT_INP_FREQ_U_0 0x016E3600UL /* Counter input frequency in Hz */
#define WaitTimer_CNT_INP_FREQ_R_0 23999808.00153599F /* Counter input frequency in Hz */
#define WaitTimer_CNT_INP_FREQ_COUNT 0U /* Count of predefined counter input frequencies */
#define WaitTimer_PERIOD_TICKS 0x0003A980UL /* Initialization value of period in 'counter ticks' */
#define WaitTimer_NUMBER_OF_CHANNELS 0x00U /* Count of predefined channels */
#define WaitTimer_COUNTER_WIDTH 0x20U  /* Counter width in bits  */
#define WaitTimer_COUNTER_DIR DIR_DOWN /* Direction of counting */
/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define WaitTimer_PRPH_BASE_ADDRESS  0x40037000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define WaitTimer_Init_METHOD_ENABLED  /*!< Init method of the component WaitTimer is enabled (generated) */
#define WaitTimer_Enable_METHOD_ENABLED /*!< Enable method of the component WaitTimer is enabled (generated) */
#define WaitTimer_Disable_METHOD_ENABLED /*!< Disable method of the component WaitTimer is enabled (generated) */
#define WaitTimer_SetPeriodTicks_METHOD_ENABLED /*!< SetPeriodTicks method of the component WaitTimer is enabled (generated) */
#define WaitTimer_ResetCounter_METHOD_ENABLED /*!< ResetCounter method of the component WaitTimer is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define WaitTimer_OnCounterRestart_EVENT_ENABLED /*!< OnCounterRestart event of the component WaitTimer is enabled (generated) */



/*
** ===================================================================
**     Method      :  WaitTimer_Init (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* WaitTimer_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  WaitTimer_Enable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Enables the component - it starts the signal generation.
**         Events may be generated (see SetEventMask). The method is
**         not available if the counter can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError WaitTimer_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  WaitTimer_Disable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Disables the component - it stops signal generation and
**         events calling. The method is not available if the counter
**         can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError WaitTimer_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  WaitTimer_SetPeriodTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         The method sets timer re-initialization period (in timer
**         ticks). This method is available only if the property
**         ["Counter restart"] is switched to 'on-match' value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Ticks           - Number of counter ticks before counter
**                           re-initialization. Value 0 means maximal
**                           period value the same as "free-running
**                           mode", e.g. counter overflow or underflow
**                           without any explicit re-initialization.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_TICKS - Ticks parameter is out of
**                           possible range.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError WaitTimer_SetPeriodTicks(LDD_TDeviceData *DeviceDataPtr, WaitTimer_TValueType Ticks);

/*
** ===================================================================
**     Method      :  WaitTimer_ResetCounter (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Resets counter. If counter is counting up then it is set to
**         zero. If counter is counting down then counter is updated to
**         the reload value.
**         The method is not available if HW doesn't allow resetting of
**         the counter.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError WaitTimer_ResetCounter(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  WaitTimer_Interrupt (component TimerUnit_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(WaitTimer_Interrupt);

/* END WaitTimer. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __WaitTimer_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
